import pandas as pd
my_datafile = pd.read_csv("pandas/pandas_practice.csv")
# print(my_datafile)
# print(my_datafile.loc[0])
# print(my_datafile.loc[[0,3]])
# print(my_datafile.loc[0:3])
# print(my_datafile.head())
# print(my_datafile.head(3))
# print(my_datafile.tail())
# print(my_datafile.tail(1))
# print(my_datafile.info())
# print(my_datafile.shape)
# print(my_datafile.ndim)
# print(my_datafile.dtypes)
# print(my_datafile.describe())
# print(my_datafile['marks'].describe())
# print(my_datafile['name'].describe())

# print(my_datafile['name'])
# print(my_datafile.name)
# print(my_datafile.iloc[:,1:2])